version: '2'
services:
  web:
    build: .
    command: bin/debug
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  db:
    image: basex/basexhttp
    ports:
      - "1984:1984"
      - "8984:8984"
